crds:
  enabled: true

grafana:
  enabled: false

alertmanager:
  enabled: true

prometheus:
  prometheusSpec:
    retention: 7d
    storageSpec: {}

nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true
