crds:
  enabled: false

grafana:
  enabled: false

alertmanager:
  enabled: true

kubeEtcd:
  enabled: false

kubeControllerManager:
  enabled: false

kubeScheduler:
  enabled: false

kubeProxy:
  enabled: false

prometheus:
  prometheusSpec:
    retention: 7d

nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true
