---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-secret
  namespace: cloud
spec:
  encryptedData:
    redis-password: AgBd7XRwIDQw/ENC2kKVQFRzcrgvTlU7deGsgiVFWEA8Y0BCPJidQbnjS1iKj/vVovaZTy9/Wd3/8u9kZefnGV8y4KXi1Nf3C/BW8hXgUlubZVGd66BKIwrpBl7ptH+2myrAC6NFWzjMHAoAYjoBD0OTyPZBXTUcbMn38b/S2nV8GOXTAKvYXuk6bkZJhAXfU7RfRAEUEoYXT1KB/Lr2RGygGdXM9rQbFh7AVjECYlIarV4D94f0K+4TAGrULlNtR/St10C5I/xF2is5PzB2dbwpud5Y6RDIhN01LuYyzO8Ajj4m5DZItMk4u9/ZY4/2f0iT15LjMxt/jcbC2VfY3xBvkekpMpccQfTVtIRLYozbGJxT1enskkQUDV2efzjltQGxqX8Wu2PFGA2tJ87EHa+kV724E0ZhckQO9ZMMVad43XHBicKe2UX1tuVz0hajISQNfAmV4DQjwojpgnsyIArK0ubYq02J2mey5qjRsifpQi/54Q/hZAh1cGuNjFCTdfxKg6OYnKcVpI8F0i2X+1+HFz6wkjNSuUfzpSzqQWawjrT5GRsp5SKKcYiZiYNFqT5/a0LQ22aG75vQjRbDAuWHdiR51qJ2wJG22vpKo1W71QgRcWff4O/wvbTHqaTMiHfiTgthkSxf44zeN2CImCPn3XSZHd0WxIo1G4tCj3rqbMwKhxl0Ws30GlKfL6hHHCN/BBzOQIdfEpP5MJGtLuluwy1Pao67/ijmm3EEH4qWzw==
  template:
    metadata:
      name: redis-secret
      namespace: cloud
