---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-secret
  namespace: cloud
spec:
  encryptedData:
    redis-password: AgCG1IRt0/uJ6WPDopFOhEEctnXaQYYvXpvsLczPpVqHvR2eQq8ZtEr8Gh58APNLDDh9ouB1pyg6I1PL3U9HvNPX3QEl9jk+sRxysAaGRYChN++qPXStc29SRiVoyuNGF0pX/AJ35b27fiSTrEvsOQ8KEm0pLYaF5EKfBJZ7jt0hU87ErdRVRc99IJME8T2Ddmout7ErgVRDAivy3DZKZqlG87fiqCzrdsjFpRvjTTyjejFqHdF+JDES+SG11ynwHlC2CkPbOALC8JSHQLsWPdGM1kb6T/slqabrACZujlYP3qEek+HdBMueMnj1Ymh9VvUnHUn0omA+rVEBaXTpyOfiwLYrBnxQsJW38q0h9HtmcGnZ1TSLFjINONGc9PG+5Wze+jgmtEk/e23XM1y4k+lEDcJVTzNB011cUTdHFyJbEBGVZSIR5LaD/ugpTBM1VblC5vJ9wEidzjFfroCF5bcJ3qByKMlS/6rYs3o33SV2YclZ1T+C9O10exa7ME4Tn1H5Cn4QAisRzCmKEBJYHVOp0R1pa6AVugPzobyNWdx6OQz7bGEyIIKGHPU9THWnSaB48kTPn6tz2k2+4P3P5o5EU/Qq5P+bEG89nicOGXLdntMAEn1o7m1DPjG3UfkYxX5WZTrv8YgnN5EBhN2WLcgYlxjPsHYf6kYpiuUBOiqBpDvp1ZxhuOh8qJeNpjnvoOXHXmEddpOAfJ96AzOp4DDtuYu8gxjsisSx8EbVAni/EQ==
    redis-url: AgAnip24W7qrlaxpNdVtm7ylyruyNB/xegcQXfHauUEcj6GQGZY/brshxPnFhvG5C3pmEcuj2m3o0i89AyvhHIut51OLYBuKl2oFaa7H9xqn6xvySd1pKEg5lPNJ22Jezw3MhOg0zufVNg3y0chwlbuem3kNYN9rCk38WyraFGiSWIB0moQ663UXXkktKlYkgQ1tm+qsKoB8heqD31QsMH0JdBQJ/dELGhrls3cgSdXC896qzorxaJKQWk4D0Qoeg11zGZGXulEeiAhQaETzFmYxW7H7wA4eWl63v+03vMy4ZxicqIloOBbFD8azGi43bry9ulixPNusEvtMGVfA5rLKQPEAyfOyWLEnF7ZD5pywCgQ2bawOhAHMboWzC+u7wiFCdqz4MzoGoPrOMM2EPNwIL4zjxggDW2zlVmw29Tltxrm2GFd+5FxCcdUtZTpM/CC9Fgzip53aQKGbP16SXaTzarZXcf+yJ3VJ9WiyfA5E2oIp460dLvyPZa7Mq4O2WrTKjweZQ4qJKYebkpfyMEio8XGKnrJZvdE66gqJRKqGPOjHgqiXha/ec5+lGFF5MW2GduPyuMxKfkE5VHukvqahlplPAx2bmIFUWDN7uKNa4NHFtdfVoch4uHRkN1nshw67vaitkIFTpcfkz8tdaean55WbeGC0J9C0oq1SPItxrCYGyA2zHwOMtd6IyR9wn1P3khfQ+IQu4bW6hChHmH1uHnr8F/g+jqeROoXaD+6b+suPsPqWuNS69RMvRkhglsCSqFt6JDwtAD/1zT2GUznEi8vMl00=
  template:
    metadata:
      name: redis-secret
      namespace: cloud
