---
ingress:
  enabled: true
  className: traefik
  hosts:
    - host: ollama.home
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: 500m
    memory: 4Gi

  limits:
    cpu: 2000m
    memory: 8Gi

persistentVolume:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 20Gi
  storageClass: longhorn

securityContext:
  runAsUser: 0
