auth:
  username: nextcloud
  database: nextcloud
  existingSecret: nextcloud-secret
  secretKeys:
    adminPasswordKey: db-password
    userPasswordKey: db-password

primary:
  persistence:
    enabled: true
    size: 10Gi
    storageClass: local-path
