auth:
  username: nextcloud
  existingSecret: nextcloud-secret
  secretKeys:
    adminPasswordKey: postgres-password
  database: nextcloud

primary:
  persistence:
    enabled: true
    size: 10Gi
    storageClass: local-path
