auth:
  username: nextcloud
  database: nextcloud
  existingSecret: nextcloud-secret

primary:
  nodeSelector:
    node-role: storage

  persistence:
    enabled: true
    size: 10Gi
    storageClass: local-path
