---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCaJLkme5/3U2SSBED8WTnNS2//O9jgaaQwOQcgYpBCbl5Svm9kM8Ak8clxBt2irkr1z6M1zk3R6TEnbdzxrYPvK1RQzdKboQ+i7c7l0H4o7DmbLENPoyNlK0pR0Di7ChLJ7vsdFVprYTtg/b53Z7l9rwMnfTA6KDEDYPohdIvKAwYO1z2poKPvozBVUpcZTn2rBb+dQPB3Z6iBuUKlm55waAs2myUWaK474PtBExI1sTkEFpjLTXhRT4yIv7xNly/gF/uYXNpKq8yi8G/CrZ1bNAiqKclwGe/kvyEGDvwmEvmYIwYkHCmi8AiFYEcbyrluE1f0FdWEiW4YAXzlKjmzxQtWSB85fv/uQzmHPVReUzaH3oz/eOB3xgZj2/WjT5qWVCI1eCLnQeYMSCH/Uu03x6yXxPLW/RrgPAsEhhLFUPagT/bvoCRl74fd0Ire+GqNgY7K/jI1FhXMTbcRxv+8o7NgjChsvwPQ3WePYv2P1hRhJdbTGp5iqFv7Ow9wJhRVr2BVxHFvoWiSGSf9ZN1ehK81Sjl7UbM6XpTxlBQjE51HlG3hOngEtg0BUrHVlT+BYWGJCr7tckkZlvrvKq5mCQuztQNEiZmorvjtUMaO/adEGsvqES86BMoax351lXCyCx53hccwZFS6y3nBeFNNpD9HUQlXkuR/7mDaQ2hqFLSioRtzvGwRVgzq+n5aLUV4RsYTbMtrRQanYA==
    admin-user: AgBNfUgYkem2wEtmMLQogbcxf5kUwJxCZuOHk+igeqVnaoc8+4pprLkPtPVcNdcwxSD+GEmL8wXoObFG2WqWz+RsuJ66tJBCXX/ERr2+nMuUGKnSKu8b3K/hkmt9JdRa5uTcc04IDdUio5WC+npPsMLZR5hBfnDBqOA65uyS0+yZWZrWk+PN8bHQVrBEA0laXGWIu2W216vtHYDT7t2F6y9xPG+BjtQPcYbipBeiIAc5AK7t8KFYZvxbyVtNwkOmVkXXkIL88abDiZAVftnvsEpfHTgYhXuoRi67sF6nebIx/dzbWP1F28uqgEi3m+1opqd7AR/+y9g09z+pl2u1EYUH2nLpPrf04/Gi33lwlq1QAcDeAV0g2WAb7VXtqhp9hUX65eiLPJdGcUbCMXkEFZBb83lcjnyAB/ZAjVyTBg50suWDxp93HorE2e6PdMioTWrmLBab4FYV4DFjvwSgG/Vz1jNXZafAlYgC9awnHh+jtSQTjA88qHpXsJlVscgCHqwMuf/tscOwfiYQjGLn86I5jVCsna8Co/h5aNBSi/BvXG95DJZuBbQS+ZVQ8zhlLlcSxOrCnV2WIsdq6iDJhe98Wi1UHK+DcSXulAhsVC2XjMVq4N6wblvhIkTBIOziELBATgZ9iVjzzp5Xx7gw37epUCEbW6nhkDj8Q2JuRMRF4mXrGNy7JKtKi+cKN4YT7+ri69ro5Q==
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
