---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgB8js7nhwU3RP+iRO7rSe3CNnEqXPqtEfoG8BAQVxmLduAlulKmH6cnOx2TaJgmFsFTt6BefWmoKNZpKApXs5VQwrIIxvsoeqjS9CprR0pP1H2unt0cvSlMiiA3Ltlr+ujdOQ9uVz+7o0KBw+D55g41zInGCwqtp0YcKTp1eBCkcfzxucKcEeNm2gHqbtGJ2PcELhjnEZGPdHP1l4KKrcUxWwBlD5zkVpiFaPF4kPUbI1orUHqPVSNHF5Q8OCNstq08hWrJROYlL044wxW1vBkKQg+OjNZJogCt7S8xIAj0Sdkjaz8fxR9rW4+jFP/7zo9D2bwz+pnURNqBIZKd0n7QHP1WVXRQuNTw7dXoZ0Mgjj7wer5D575d+pN+muiBFA0fwrhqX4rbYXfcEq9BPrpUniIoystW1TKFLnbqCmSUMJ0Y1GJfae0414/XOeWLDIMGqR4aa62bk2ur+c1TI3QGrp0cEJQCtAJnCyX/bFKHImkd/sxMARrY4MR4VBqVkR80NA0c7e/4brFyXMMQjrnmH/uGtWnkMk4STabatcEtak2Siza8uwqDaN0NsgwzXp8xIYPU0sgbpCqRBR+uYZt8jKIuTQxX0oqh65tbaN24bLWbzpLh+6lpC4Fn6zR0bu5gUcuEyrGg+8A5K9qtnjf9pilab6zvVGE5p+FQuY8MkobcgtvcIJT8FsDwt2TOJ+Exwx/ViOlkfg==
    admin-user: AgAx4c3NXI+Ths1qU/IEups89A/rSXX68i8kmLtDM8Q7EJdUQo0rvrjRDmcv4Hu8CgOLLjiyYmB6qPDbDuVEcJi/e7E6GYnDQ9mZcKmJvBCB3bipYlkm8SNlkU3HSoMLk/24n3XR+nqmwK7CeyCbcIwus9Tq9RhFTjzlHHK+Pc8aaFXX8KYrkkyHA/uACZRKWHfGZFT0OaDzdJstWSwZOAjuiPJUR6YnP+TmhM6t6D0zu7ISHajTTF1KiZhsDE7mYXy+riHuhSeOOHCYWPxM1/qdwZ65rretgBMREaIWYbjEZd4ZlZeCKWwA3+eaN63bWNu8n40lfgAxX+i5Fz6gf7j1DUyuhhlokj1RYeLBy9FzdaJXJKhybsG6LximJTj95B8b3dkoFLP2tzJWfm8RUkriQQjH4ZcKAkYTtgHFZtMFLs6foAxaq/NloqYFK6g1/oQ3nv9Tadn0fms5kEaW5hs3m6okxbQCjHBbnGJMdE1WLKMXClloJ5z6pL8xr3DHlb/PrDFBg8UBJmDEVRhcCPi5IibvJewxKNBSrnZTz5OVa0IFVV5UX5nS5ksxjTcQqTHRQJQGL7iS0nDROYxnXXvMDF550xODEzCfb1z74SG8zPWmeeb9L2bOIo3843Wz0WSIxVpSQvphB0nnMF3avv4uofY0R8qaEky1LrOPEMenlAK21opGGnARt3BPxrv5wx8R2zAjYA==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-secret
      namespace: monitoring
