---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret
  namespace: default
spec:
  encryptedData:
    password: AgCG3Tea6L+b9pT0C+oeoxXTaa2/0pYVCWRnd42qK4C2RXi/pYw2BgEtgK8qZOR4iv3CyDp1wUs6zBSI4niXPyNTIa9shnfdqZL+1n2WvQWgdtVE0dFrVmpZV3ZT6ZjbNq3XTxzpTuUDKy0RHSNhKGxq/nbuXJxkSw/jldtd5CJNdOfRln86PMZdA1ofNE59mXsTAmFty6H/ZfQYrx3gBhUDu4WtXK0GfdZcJki4JPMMF9s1U+o4gdZAGCLVL4ZMb74vvblMEtECrkpc51UM9CVtXp31Wk0ETMdJclJtjGiJQT+9yyo6YbSs/Y8qHUrFk7W+kbYWIstKcOJLwaI7Lw2HEASmiDQX0NtUeGlfEPM9H9zSVvcGrjChcryastm0lr/qmtKOF3YM9pjB5DzV/qKRFd3qBYVNKvzv7BXuFCj9pJBtb565ETFgO28bcC07PETWlZbBVCd6uuq0tr+jttdiXTXeK/RlRQ00+gZyLOJJxfRFgMwUAv4jU3PLxynABJeg2XGvC8B3TWP/JiiYxxxHBMJ0qFroDX/BqWtxtlGbusfEw6wmp5VoPzxIwThvz2t7P7QD/ytbufJEjKQk/A01F2UgZfede2nFrth6JWwafBafjFfgKH4V8EEGTv1q1PllP7mmj51ONODGK98P5HDiYNseYxsUIxweCigvNPUkU0yq5Qs6s1Dh+ofX6XOBl8Oj1tL/r2perOOcOg==
  template:
    metadata:
      creationTimestamp: null
      name: my-secret
      namespace: default
