---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system

  sources:
    - repoURL: https://metallb.github.io/metallb
      chart: metallb
      targetRevision: 0.14.5

    - repoURL: https://github.com/RVinther/homelab.git
      targetRevision: HEAD
      path: platform/metallb

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true

  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition

    - group: metallb.io
      kind: L2Advertisement

    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
