apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
data:
  settings.yaml: |
    title: Homelab
    theme: dark
    color: slate
    headerStyle: clean

  services.yaml: |
    - Infrastructure:
      - ArgoCD:
          href: http://argocd.home
          icon: argo-cd.png
      
      - PostgreSQL:
          icon: postgresql.png

      - Longhorn:
          href: http://longhorn.home
          icon: longhorn.png

    - Monitoring:
      - Grafana:
          href: http://grafana.home
          icon: grafana.png

      - Logs:
          href: http://grafana.home
          icon: loki.png

      - Metrics:
          href: http://grafana.home
          icon: prometheus.png

      - Promtail:
          icon: mdi-file-text

    - Networking:
      - AdGuard Home 1:
          href: http://192.168.87.60:3000
          icon: adguard-home.png

      - AdGuard Home 2:
          href: http://192.168.87.74:3000
          icon: adguard-home.png

      - Tailscale:
          href: https://tailscale.com
          icon: tailscale.png

      - Router:
          href: http://192.168.87.1
          icon: router.png

      - Traefik:
          icon: traefik.png

      - MetalLB:
          icon: metallb.png

    - Management:
      - GitHub:
          href: https://github.com/RVinther/homelab
          icon: github.png

      - ChatGPT:
          href: https://chatgpt.com
          icon: chatgpt.png

    - Services:
      - Redis:
          icon: redis.png

      - Helm:
          icon: helm.png

      - Sealed Secrets:
          icon: mdi-lock

      - Bitwarden:
          icon: bitwarden.png

    - Daily:
      - Nextcloud:
          href: http://cloud.home
          icon: nextcloud.png

      - YouTube:
          href: https://youtube.com
          icon: youtube.png

      - Gmail:
          href: https://mail.google.com
          icon: gmail.png

      - Reddit:
          href: https://reddit.com
          icon: reddit.png

      - Calendar:
          href: https://calendar.google.com
          icon: google-calendar.png

      - SDE:
          href: https://learn.sde.dk/login/index.php
          icon: google-classroom.png

  widgets.yaml: |
    - search:
        provider: google
        target: _blank

    - datetime:
        text_size: xl

  bookmarks.yaml: |
