apiVersion: batch/v1
kind: CronJob
metadata:
  name: restic-backup
  namespace: cloud
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: restic
              image: restic/restic:latest

              env:
                - name: RESTIC_REPOSITORY
                  value: /backup
                - name: RESTIC_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: restic-secret
                      key: RESTIC_PASSWORD

              command:
                - /bin/sh
                - -C
                - |
                  restic init || true
                  restic backup /data

              volumeMounts:
                - name: backup
                  mountPath: /backup

                - name: data
                  mountPath: /data

          volumes:
            - name: backup
              hostPath:
                path: /data/backups/restic
                type: DirectoryOrCreate

            - name: data
              persistentVolumeClaim:
                claimName: nextcloud-nextcloud

          restartPolicy: OnFailure
