---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: restic-secret
  namespace: cloud
spec:
  encryptedData:
    RESTIC_PASSWORD: AgBgH5s3cmzIQGQWApE5PSZCnP641joShEL2k+bBcI7W2Py5b9r0pOkrFxklxLMt/DobY94gocV+lEH/FWaDDKLwH5pjzEHyl80p6nTJJ4QIhrXie4Gz4lQ0S41LUEiM2RiZvjLawpxqeHKSdf9edpHis9FcwtAWdB1Yf8Mb1jQ/7VJKN6xj/MoWS7cqpF1w+3qQlSxGAn1LOFe98UafLRMmxR7n9Kh7x1cazLCBVjuZB5D23NheZM+qn2MBDrsGx5oL9wIFS/5ayjIO2UWhU1LynbN8Zpq6iregQgvIHDFJVofnKQT3EAVBaqUKlNxfz7zYytvGWOIzwqLE2TuVo8d73tIGH8/iHrBmCZUpOXUsCBjaEWgYwzm2uJu69FdSpUaOnMLG1ahQe7G+XPCzHcXkB0TZO0k+ZqB+wlcaBAz8Cq89BZCoj/MVNMCF88bJZdAHyKMAkNvU2xm6L5pCF0rfs2XnpFvGM6EcWPVRNtaZzOaEc4ywJudWGUfMJhVcSBozzEDy1rjydIEzT75sDXwCbA4lQJaNRHfyl4iboZKUZ3eWLbkX+D7Ox0zvXCRClvSqWBOo3OfvJu6BjB2MBRKrn2PEGUTNPWa/XkrYLND8VZeQl3uPrdXs9f1bBVIc5VeR+M70ybB+68UQMb8JxPMklyfKtnqF0txGhY/Ee8SotNs1v1V7z7uKF5DtdWDY6GERzrGLr0USPrOH3olH4MxJbX7gQ6tXB8iM+bww48dqgQ==
  template:
    metadata:
      name: restic-secret
      namespace: cloud
