---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: restic-secret
  namespace: cloud
spec:
  encryptedData:
    RESTIC_PASSWORD: AgCJEVuYSkPeDnQlxJxBA6Cg5vgUhpWCEiKuPOdGvTgenW2JSJ2vN4hiMtE8r7rIoFU/RY7nFevrO23JAkbCjnlUv35fpK6xGKpRdG0b5Utmt7wyf+f6Z9CfJBE0qOiK6/SXgGRCTzpJR7r1Eiw8VKMqsRsfTlun0rfmAJeigz5PJaZQKTqFc6yJ86XITFtAe6wfyiBrm83M9FxXs3lMXq5pYF4uhFO17PrwKJZeIqHRz6we573d0UnDQJXBR0ZnGj1NqsUjqDgtxHL2QOJGEp093aZ+e7wSCI5+DtcxXT12Kwa8Exc/etH1AikLOHlTJBaFienSo8ekKIhRuPF++pxP4BcgL3/mg8du0CGEnkdeT5QRCI+XZs+A+8R8UWhi9Sy3Y4Vmn2loOYGOLVKBijM9s1gydCZZVKwG/0y7EdOaw+WX3uCKqjyOfGp91IsHTbzbfuczzYld8MedyalQ8C7gt4xzrMlD8z+OqMrx49kWQPPGInRfgYsNOx5vhXpYSfcywfSyZZwzWw2/5B/VGul0hsabp4ZGmc9ld9inojtTqiOtrimJBNViEAb0k4RTLgVxdGlRQ2y8bOBbcOn6Sg+FRKcW/teHaU6PTNb0+DCNqqnRwaL2Yl+llzScRIu3YExtoCKy09gbLWno904yVKMnw8bTpeiX3xSXs3wv5Jk5MEnmjm2khBRtahvC6MBD0z5HPMoijKI5zHpuyNyiXXBaLCFK16UUfUE7+TNWB3XYFQ==
  template:
    metadata:
      name: restic-secret
      namespace: cloud
