---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-secret
  namespace: cloud
spec:
  encryptedData:
    nextcloud-admin-password: AgCeyqLliWQXGgU8JejEEjomiKmYH/UNzAXNd8AaxVIqo6xoOp4trHWmT1nzA/C2Jvke/j2L0dX4NdMv0bX5STRk+p2EONSlfJV+CJPzR9rdA/FjgmW7i6a8xMrIQC4eGeRWzgYHeWth02U9ru0MrokWvtRTKcLDTEMjfl0xh3Zwj0viZAEJXT/NLuWJLqDicgM2FIUeLZtMAQ9eHMC/2FhmzjJYFVZEds/RB4SAesq2CNY3F39TC49e9PKAz5MkLLJ8qqpPOCYLPw7DOxjmKnbjSn6hWe1VX/zXDco5rK8La2eKJAGX0+Hjz6J7Pd+vQj8/hdODnu5xxYKVtjMZHbM1lyiEQVJl6zEgy/7dYePqXgTl8SsyHUYL9mt1MUOAFfyosDZSMCkVbDYTNI9ZPcxCguIg3k1K5vUjDQ/Bm2CBJLrviBWezY+esKr6P3nKi7qXn0w3eVb31se4Op2WC7GyLYs1C2X0Elxr9lzk+svOiT4zn+bw/unq6KenEOZi1VY4Q/B65dt/Dkgls8geC+RbroFyrkqufHOUFj8Xt/PU0xfzcN8THTYr2ivENKggaAjHk0D0kFEl33VcA5e5ufaOx7hOj/6pEC6675wGjQFQbj1s8f5SJnupNr6oIMuYCE5SgWBUc0DCAMVqDaStRCCr3KYC78qx6TFSKMjvNrOrCmG7WYn6XhnjAJnz40LTlm93470qxg==
    postgres-password: AgAjcH6/9Ucl14zSBzn9j4rYXvmpMYdcix2czPJ5vZXwgY3nJz4dCMEfg/4m09K0UVv/qIqWg+ABHxKrEmKZ9wtTi+RWm9AUfIeCuVhidu7q5ru2jLyw52pGEr18d7neO+lOxcEX+KJ/0Og+9GiGHs6pAmLrerTbws/Kv/AUcQ3ha31GQyJSCdQ7l1Vuz23Uo0pZEzG+B8zSFu1+3wQL8Ey/jFqgINxaK0kg/rMaGdJfgzzo1wE6IPPhgGOBrO5LOwmrTCi8W4qCfIR2f8VWVFX+ticoShesgrdgIj0qMtjcT8Q1/fcVwvUbKvZ+FFYcGShD+U3EEZI3Jh+rP0Eff0HQo51smwfPtbnSfYV+8Tz1k8syzNrwk1/wjU5vujJKpGms+47pnGVFgItZX+PYPDFcIzEeuRdfMJqSpGg8yYtebOWRN7aaD+Fue7Q7XE0l7LOwr9EYHIr6jpyaNunQKbzsiungV1XMYqaV9mF+N6f6DQjbLLsD3luclxjX7D/3BWesxUPK5BncYLAIbC9oYnfm5TbI1HQLF0ojMxHuTJ1QY3wzuepiVAvIZdPBVq6DF3ALJ4KH1pwaSWKmbrGYpwV3fEMXKCMoOrbDz4NKC+8wbZ/wxnTr+nErf31obC0lePDHbyKvAiWyvLHFzQpOw4zTQW8XjuU/gyEq/ofrs1oSzRhCWl6EZAtrPgm2EDjhC/oyvG0JyalAIeVAwcOUzQ==
  template:
    metadata:
      name: nextcloud-secret
      namespace: cloud
    type: Opaque
