nextcloud:
  host: cloud.home
  username: admin
  existingSecret:
    enabled: true
    secretName: nextcloud-secret
    passwordKey: nextcloud-admin-password

internalDatabase:
  enabled: false

externalDatabase:
  enabled: true
  type: postgresql
  host: postgresql.cloud.svc.cluster.local
  database: nextcloud
  user: nextcloud
  existingSecret:
    enabled: true
    secretName: nextcloud-secret
    passwordKey: postgres-password

persistence:
  enabled: true
  storageClass: local-path
  size: 200Gi

ingress:
  enabled: true
  className: traefik

  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web

  hosts:
    - host: cloud.home
      paths:
        - /
