nextcloud:
  host: cloud.home
  existingSecret:
    enabled: true
    secretName: nextcloud-secret
    usernameKey: nextcloud-username
    passwordKey: nextcloud-password

internalDatabase:
  enabled: false

externalDatabase:
  enabled: true
  type: postgresql
  existingSecret:
    enabled: true
    secretName: nextcloud-secret
    hostKey: db-host
    databaseKey: db-name
    usernameKey: db-username
    passwordKey: db-password

persistence:
  enabled: true
  storageClass: local-path
  size: 200Gi

ingress:
  enabled: true
  className: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
  hosts:
    - host: cloud.home
      paths:
        - /

livenessProbe:
  enabled: false

readinessProbe:
  enabled: false
