---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: paperless-secret
  namespace: cloud
spec:
  encryptedData:
    db-password: AgAgX/CzFMdwRzVm0g2r3QUJQwDmAAk2PbyNhBIFgYcEBsk5oSh0N36kZxnNCKrem+LAoI+t1w/rEu3Ud/t587+r38J+zYgPcyDo3hWWRvtS18OqsNOvhZBrnZbdHS7s2jRSW1RgvUImMZ9KU4vmCfrdAku2oi1hwvyIu+XEnDBETk+GENBjW/uSPCWMV2BzUiyRuJ+AvrF0JOjXUlF098YZqLP5exI3dZbEbFTh3XjsjgLlgl0sTF5/LxcQsOaKg481KDa+b84D3DYC3zYLCmVFSdHY5jSoKMG38GbSMfCQQaQ3EhFpTOGsJh1nT2e4Pq5G491ADGV8by3yTz5CdjGaB8ReFlQQAnXHxFlCvNxoM85WJVu/ZkCxn7c1jTBdx4uyjZ5DRarI4T8jiCC2REPpDtETM0Ji2sMsSZVLUFU8t6zkv56V0U8rZHh4Bbq2iTuRAgqExlfEw4KqSQkhD/q2P4GUJZs2QcO86z8AVkqA2/lLwQZy7w2fSNOmflg972lrE1YE9Ky2YuWQ504rCwP6zo93vH5E8vVObnhZ96AgQZ3nn7mHgxq0dyyHPBCjBHEZdsZ9ai5qOBH/+xCxoej46RxgrFtCVvI8cntp0HD4b5MapMP0RKcnO3ROvmW/KkMVIiZ+Ok75rw7aMYNieYJOomMOTH7IYCfYoe4jl26TFbSmvnGOOUFszTOtrfpxN384lJvFOaZQoVxvGnnLYGVOtyHaHLgMkds+Lg0Byrc2Nw==
    paperless-secret-key: AgCCRbG3Rw6W+BmZUSck8xlfisaPNMmtvzqOR4UGlRmzC1c5LQYZ5uQ88g32sbkm12Sr1OAUL4qdJj5J1ZIp9UTwJmmNUqvY0yRi4G4RWOpRGYtfdhRfb272W1lsuyuEcHgn89ZdtpTfHShMs9goueC0vDzzHheXkBd03um3rkN8RGdqCtdZGghO4ejTIOI8oaxS5QitbR9zTP+aAcRQBIcP8LFw2mEoF1bZA9YeT4Km3AAHx4x522QKDfkFSgX46lSNBlf6f8DtZa5hWx2miuthjCVwCY42V1rczWvhSNVZAitEbxZCr8eX16J9P/ZNpQ0pDe7C33LV6FsBL/Rn22QPmmijaLpGjR53xWRf4vPx12BbqKjpEb1K/2D74ZvW/3+5r1yt11rHRiXHrMBSb3jEjwN+5zBYH6VElhp16Wqjz5qGHLLdhIubwfI0oG8T5SRx50mqp/gY18nRnHUBnULaSSfLJspGDH9QToDubKiazBUmvlrwyX9/IO+Y/TPTHYar+e6ocSMbKaIWHsNCxpfgukTRb6R9487LXAFWCzvPpM3vFlvxCGC/7VVjKdw9A/TaH5KmGcfWpki19bf/aAsZYyG6M+7bXtG3y/77c6vG7+Cdc15id6Snoe68Z8nbo63kocVHfnDUsp7NoiypJTkh4ecVmAEKRCk88IpLh9H8fiEOJX593IBzinoswHpTCGkmE7/cJFX2L30wX3UUcCdkhguqf6wvuMbRxU++YUx4UA==
  template:
    metadata:
      name: paperless-secret
      namespace: cloud

    type: Opaque
