paperless:
  host: paperless.home

env:
  PAPERLESS_DBENGINE: postgresql
  PAPERLESS_DBHOST: postgres-rw
  PAPERLESS_DBPORT: 5432
  PAPERLESS_DBNAME: paperless
  PAPERLESS_DBUSER: paperless

  PAPERLESS_REDIS: redis://:$(REDIS_PASSWORD)@paperless-redis-master:6379

  PAPERLESS_TIME_ZONE: Europe/Copenhagen
  PAPERLESS_OCR_LANGUAGE: dan+eng
  PAPERLESS_URL: http://paperless.home

  PAPERLESS_DBPASS:
    valueFrom:
      secretKeyRef:
        name: paperless-secret
        key: db-password

  PAPERLESS_SECRET_KEY:
    valueFrom:
      secretKeyRef:
        name: paperless-secret
        key: paperless-secret-key

  REDIS_PASSWORD:
    valueFrom:
      secretKeyRef:
        name: paperless-secret
        key: redis-password

redis:
  enabled: true
  architecture: standalone

  auth:
    enabled: true
    existingSecret: paperless-secret
    existingSecretPasswordKey: redis-password

  image:
    registry: docker.io
    repository: bitnami/redis
    tag: 7.4.3-debian-12-r0    

persistence:
  data:
    enabled: true
    storageClass: longhorn
    accessMode: ReadWriteOnce
    size: 30Gi

  media:
    enabled: true
    storageClass: longhorn
    accessMode: ReadWriteOnce
    size: 20Gi

  consume:
    enabled: true
    storageClass: longhorn
    accessMode: ReadWriteOnce
    size: 5Gi

  export:
    enabled: true
    storageClass: longhorn
    accessMode: ReadWriteOnce
    size: 5Gi

resources:
  requests:
    cpu: 250m
    memory: 512Mi

  limits:
    cpu: 1000m
    memory: 2Gi
