---
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: emulatorjs-config
  namespace: gaming

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: longhorn

  resources:
    requests:
      storage: 5Gi
