---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: emulatorjs
  namespace: gaming

spec:
  replicas: 1

  selector:
    matchLabels:
      app: emulatorjs

  template:
    metadata:
      labels:
        app: emulatorjs

    spec:
      containers:
        - name: emulatorjs
          image: ghcr.io/linuxserver/emulatorjs:1.9.2-ls173

          ports:
            - containerPort: 3000

          env:
            - name: TZ
              value: Europe/Copenhagen

            - name: PUID
              value: "1000"

            - name: PGID
              value: "1000"

          volumeMounts:
            - name: config
              mountPath: /config

            - name: data
              mountPath: /data

      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: emulatorjs-config

        - name: data
          persistentVolumeClaim:
            claimName: emulatorjs-data
