---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-secret
  namespace: default
spec:
  encryptedData:
    admin-password: AgB3kEoJ87TP1j8sg//woaUWDXXRrgybH1SaJCrlt8CMCXNPiziN/CzPUtaI0o4TDHXiwZOGYepFsF3B5N6nkiVvz2a8lSZkjFyzEmbYPZ8rAU1IfnHYmM3kSjCHWoq4KYav9ASpA5v3FVH1yi4Ucm+6Ejnhbrkfk+tTofbG+F2pES0raap3s0EiQNpFZBRo5PGxsQGzEFntri/62mreAclw8+NcwzoUaMi1wNk4KzHqO2Ke3+0mj3r6kEjdXyIIJ0HMPnJ8XnWxUkf/2BDKcC/NQxf/FuuGUOfnyItTizwoJUQ1RDJz0anqV/e9P1nlgM0+b1lOw+TIszqD8wPYLzVDQVhYtPt109o88CQPhTuS17c7pfPrPePAgcurhW+utUWByAcg/BEHlpb9SeR0FAp6PGKrCqKcqyWfulFmIyruIewlEX0FDC3mOTtarxmwuPrLLFK2/dJSmrOMRtgL4R+dtu9nVbLvfL+E06TpCJY/8tgxf5uAkKV8cUM9+f4alOpsS1OpJQrLDQnewiY6ZqulYFgTiLfZp0IxauKzoowO04ekdMcNhwCaczy9GaUM39BgInd7ID6Z5uQROp3JoJPv+7zEl9xRwvByPT24BKX8lubAjfaug4jNUs1zDzWu7qFmrbZpbydUKP5/7o4QebcF1BLT8oReQHHK4hY9PvrPRNLJRXRxtcbN6ErlobBMGDCtILIIuGBA0xQW1ws5Jsk/NZCh7pumV69FxoOrM121tg==
    admin-user: AgCgWiv1M4NtIUKZuLh5DRvizfNfQzLfSAeKB/XDbWKvB6m/k4bkXwzpus5bcJaF2yuDjq2+HwPsVXCEJS9OqaPFk+FTgjuvnIz+cbeR4RsZbDQgMV5W+0SVz07bjfrXCW6MJuA6eoIXbzKws/4gXsimsaUyKd2+a4uHB2+XqIhTUMhvDDGQqkhPbmhQZFfwOE5kuSguwyiN3lW8XhjxDNQKn0TXGHdHz9uNFNqE3xpQlM3+6Uu2fJCrqwrc3Xsl5Eee9oq/7FkpIFdtCFqj6atUrxj+k/8O/h7ZZzCab6/eA161bwyTdvn89c1dGmA3Xhg0Zi6/NfnyhRYQiojh6LG/HM0k5iCwcfSQcT9Ih8dBobkAlaBAlZdbKqbBeSsZHUFyzRKJzfYXuDHSD+3JV9Ag0ZnnyXASf7p0QbJK3CijV6xJSqyq6Sy5A+kbk/aznimu4oe1nDV8JwahFLyb5yLMQi+GnUPgPF34GpD+PNvEMmJp8M1WFlshRx+BO8CIHZSpG43OEp3yIQfCa000XGkb/kIj/mOnulQ851g6+QJaNFAKW8SuJ/9siY6JAtR3Lab1YRwHbQkrVv76X1KpSlzVNWpVWBwBBt9We18c9qIyjV6+jSfXw6UJWNNq49mxcpsc53cfurjihQdY5oeZMe0m47m6u2mxs400pZqOt3ufQcPrAKMy05o9cHqKum/swicCO2AP1Q==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-secret
      namespace: default
