{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "grafana-admin-secret",
    "namespace": "default",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "grafana-admin-secret",
        "namespace": "default",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "admin-password": "AgBS+9RWPaS3KKnnS+zomwHyxHKtOv1lIJZNW/4Ogx+MEUPR4Q4E6b0leWOtX8V2/6UCViJLGPLIdbb9qf6zxD5E5LB+GZW8o01KixEC72wlOfwNK9hCCPFtTDeqifP3nReBcEJY+mmskYUR7zyqhzaQrZzHkfm5cXgHLbWkNiyAPiutqEwy7EJA8jYE7tRf9BNQ3D//2v9EIfhuttvoV5NtA3PnvIVBI3iBmF5ScTI0luvA1pv/HnPY/YRpkLAjLioJkCt+VctMu4tM6awBxbUKDtl8KFUrYoZC4A9GqpV2btdxMVn5De10Qqi3iyLIkMjAPTyFfUS4TMxGlP81K1v9feZhjfaP2/Nkob7WMhdDTxWfkgnzfbjIrJNSyHtolIDUrh00nCsdDIx/0ZVZOBaDgAI951gENn3eepwqYJGxwxIFxB+NrrfT1ylNfwPTVp75YvOzQ0BX3bi1O0lJDFoan9uDkqOky7pspSmXy001g8GzxR0LqNBXv3iQ8qj/cJSETpoCz+aScM6Cv3EyPHSGwHALF2rig05qWbw+QnhJTOvdKnbmRP3EKVTicnHVikHWONoGR8zMR/uAjXhEkDmHrxQBgUWHB31t46MauchF+EmjmqH16l3vFsTiKyxKzNRRUObN4s0skPPq0uG70IXnt3WZwj66KA4hbZ0phZQh0MzZHuWOZIalaGKkBf69OvHoq62P0SfnvL7d2ehuP89YyjgQJ7CfQvNqvSyC4W0xsw==",
      "admin-user": "AgANn7uIjLkeD4RqNqeyUskJYZFRJipSi8tBsOjsZYzCBq6YfhsdT/G891rhhfiTcZ/ysjcsJjkusv15WecOMBisbYW0DvpTGv/xoBeCIzKJH9L5FFijMX0xBb/Af7+X+zo3pzmOOK2CtFC1t3fjQ9u3cBm116ItBlDMKOfxPqTKMNZGLH2cDLYMQYSVBZeIh+kerDaCRRo8uCsuOu3rOr9hngF9UYwps6eOeoh+TNvsrlJBundZUDNBz2yzsJVcYnuVr4oeCCQPLoeWvKk08LF/wpoXPJ19+rhYq8zIGnEYBR+xRSRSyjgIfjuLFBWkVX0cRZzgWbvl7bxgDiLHxh6eYQzAm7Or6XnVutaPS27+/d0pXdiMKhcCPEyCo4pFSCInUdH00Hy5QbGbsb9FAv3WsdC2F8ZTDH8eL+MVYgCTxLc89ssFtIySp0t3FnJ+HucRwUZHq11bkuB6zFLpc2Y5CkAcO0B9FDOIIw8pwsG5HhBRs3ZRlqnb4qTxmdZql4/cVxNg7oRfM2rbUwwgUg9MRTz0Qfm1UtTAO3ZFquBqa53lhQRTlu0tuqGVZxdNqXvTFAALS0TGGMjv6dFJEl9XIkxbKPahpVO58Wxs+apW0byEfbAtxYYPBtUVin4/CBtHlQPxMu5JLOFoV6vPPurlGAaowK0Wpa75AVDa9TFuoJtEIF+7HDWx+0Zzz4i6NXlQuuw1ZA=="
    }
  }
}
