---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgA3MXa+nk8DvuUQR0ZWyqyJ4zo/kAoxir4a/Nhe2uwKFgq0oRqcwzLeZh/XUJVrSdf4SAymKwGZwsWXNeB/GGEXDehBVD6eckAdKj6hPRdLuMcYIoEpupF2kFkC5NPZMtxrHDsUSi/rAWEodUCzdd0+jYex8A6ii33O5V5OHTQJc5zbyYI8tQsCgrbOGxIjfPy/0SH5Gh42C4ocyNlO6do4RpcAOutTB/Fj/nKuPgYAuLen0zToqaIknz01kq9dY2Htka6kG6dUOHtxJwmoporMf+C6xWpS+ss8XsYA3jqzTMl+ok8kCO45CXsl1Hf1kq+ToT+h5wbSg3Kpvb3tfnJubhJPeo9ZLRyJ12qEcgGPdtvJ2uYOuI6wJsv3H2Om+VoF9AOamWrMzGvOH6REekSK50F5U2EZrG/srEUx9trjGzss+lE96DjZ3gI/0KXAWSELPHM2LCAQKslZGUDGn6G6bCc7bNs4k9CnKampc78lEaK8anTWAORUvKXeF9Gg9/xId+U1v28GNIBBSWng0r9oBijp/wM7Ynk7V9GhEyM6IJPhTridz6Z/r8zrfI6pULiAudmCA1zjCIGFvaCHf13p4mIZhZzjLbAb10/G/soZIfNML8oxTYm/zSHi3WZBibPUT7qj1E4huD+IRDxBqco255b5X0TmTUiXys3ossU4lQvVZZlry5ZUmeQZMSu+py1AHZrpZtSKhZ/xsspk6e0Rt1yaZFEJYRaNZSx8Yn7VAw==
    admin-user: AgAteH8+g68MF7JDS0GXxMvMPsu9XO1DpN6S8TYnjzso+CXfcGy6Ke+5wgynWV8tEOhFX/dpK+aHoxK3aMLyOIAlzUEHFLKJuLp+TYQ3hHcHBk1qfUbx6sGQ0Kjn73DkdhvoXySYO7m5FMVa4y8Vg9DwVXnK3yWSQmdpGj31DsR6hH4eU3CPo+ov0Usv5LhXbp6TNinx01HeBFKg+uyyFRdn0Yr27ZagomaQoy4qEIm93IoxHE7Drb0JmKt0VRnfj0IMeZN1uk3zVKVTZ5GbdQ2uWq28eeNzkPIrf53BqXTsr98JvVREIbeD9yy5olDis1g1ocOeomUNhG7waOZMDLg6jvgovkSbCibTOiAlyHdy91nUz0OaZZphUw+e5i61lxCqZepiE9OO1FV7OnJg/fS0bSXYMfL3Q5c1fk/VwwK2dVMTwbcjg9/mE4p7y7SxPujiILlFhuJxzoH/uPNHS4ZaPLUNDaNFdimxS4nc1xk6rXV1W/oD3x/tamzKCQxbpG8UeqJYp3M0ImBWQUaULnWZQTgUUM5RliHavw3+BtmCLy02h7Gj99+AImcO1C7D2GW8a5B3w7LKZjk+T+cNMNY99t43dhtkIdUIDyT1n1/8EXSzBRo/6MRmp7ism2peaAix5EFc2TsMhUGyQHSYMqAAtayxueNgXbjWL/iuJ6eAFdkETOwr9QntrC6KMiOccbtqpm3kSw==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-secret
      namespace: monitoring
