---
admin:
  existingSecret: grafana-admin-secret
  userKey: admin-user
  passwordKey: admin-password

ingress:
  enabled: true
  ingressClassName: traefik
  hosts:
    - grafana.home

grafana:
  persistence:
    enabled: true
    type: pvc
    storageClassName: longhorn-retain
    size: 5Gi
